schema: 'https://demo.vendure.io/shop-api'
documents: './src/**/*.graphql.ts'
generates:
  ./src/api/common/generated-types.ts:
    plugins:
      - add:
          content: '// tslint:disable'
      - 'typescript'
      - 'typescript-operations'
    config:
      namingConvention:
        enumValues: 'keep'
      maybeValue: 'T'
      strict: true
  ./src/api/common/introspection-results.ts:
    plugins:
      - add:
          content: '// tslint:disable'
      - 'fragment-matcher'
    config:
      apolloClientVersion: 3
