schema: 'http://localhost:3001/shop-api'
documents: './src/**/*.graphql.ts'
generates:
  ./src/graphql/common/generated-types.ts:
    plugins:
      - add:
          content: '// tslint:disable'
      - 'typescript'
      - 'typescript-operations'
    config:
      avoidOptionals:
        field: true  
        object: false
        inputValue: false
        defaultValue: false
      namingConvention:
        enumValues: 'keep'
      maybeValue: 'T'
      strict: true
  ./src/graphql/common/introspection-results.ts:
    plugins:
      - add:
          content: '// tslint:disable'
      - 'fragment-matcher'
    config:
      apolloClientVersion: 3
