module.exports = {
  saleStatus: 'incoming',
  productName: 'CSM Alpha',
  secondaryProductName: "Offre d'investissement n°1",
  locationName: 'Parc des Birunga',
  locationCountry: 'RDC',
  estimatedNetApy: 0.173,
  minInvestmentAmount: 1000,
  maxInvestmentAmount: 10000,
  currentProjectInvestmentAmount: 14580000,
  totalInvestment: 18000000,
  minProjectValue: 12000000,
  energySources: ['hydro', 'solar'],
  electricityPrice: '0.1524 $/Kwh',
  availablePower: '175 MW',
  contractDuration: '5 ans (renouvelable)',
  operatorName: 'Big Black Green Services',
  operatorLogo: 'https://www.bbgsmining.com/resource/img/logos/bbgs-green.png',
  operatorUrl: 'https://www.bbgsmining.com/en/home',
  engineType: 'M30S (10TH, 1300W)',
  engineQuantity: 10,
  estimatedDeliveryDate: new Date('2023-08-31T00:00:00'),
  estimatedLaunchDate: new Date('2023-09-07T00:00:00'),
  siteUrl: 'https://cleansatmining.com/csm-alpha',
}
