import {
  AssetType,
  LanguageCode,
  Product,
} from '@/graphql/common/generated-types'

const incomingMockedProduct: Product = {
  name: 'CSM Alpha',
  assets: [
    {
      id: '62',
      type: AssetType.IMAGE,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      mimeType: 'test',
      tags: [],
      fileSize: 1024,
      width: 1159,
      height: 773,
      name: 'activity-721-1.jpg',
      preview:
        'http://localhost:3001/assets/preview/22/activity-721-1__preview.jpg',
      source:
        'http://localhost:3001/assets/preview/22/activity-721-1__preview.jpg',
    },
  ],
  collections: [],
  createdAt: new Date().toISOString(),
  description: 'Sample product description',
  facetValues: [],
  id: '1',
  languageCode: LanguageCode.fr,
  customFields: {
    saleStatus: 'incoming',
    secondaryProductName: "Offre d'investissement n°1",
    locationName: 'Parc des Birunga',
    locationCountry: 'RDC',
    estimatedNetApy: 0.173,
    minInvestmentAmount: 1000,
    maxInvestmentAmount: 10000,
    currentProjectInvestmentAmount: 14580000,
    totalInvestment: 18000000,
    minProjectValue: 12000000,
    energySources: ['hydro', 'solar'],
    electricityPrice: '0.1524 $/Kwh',
    availablePower: '175 MW',
    contractDuration: '5 ans (renouvelable)',
    operatorName: 'Big Black Green Services',
    operatorLogo:
      'https://www.bbgsmining.com/resource/img/logos/bbgs-green.png',
    operatorUrl: 'https://www.bbgsmining.com/en/home',
    engineType: 'M30S (10TH, 1300W)',
    engineQuantity: 10,
    estimatedDeliveryDate: new Date('2023-08-31T00:00:00'),
    estimatedLaunchDate: new Date('2023-09-07T00:00:00'),
    siteUrl: 'https://cleansatmining.com/csm-alpha',
    descriptionPicture:
      'https://cdn.pixabay.com/photo/2023/01/09/22/05/gorilla-7708352_1280.jpg',
    descriptionText: `Le Parc national des Virunga est un site classé au patrimoine mondial de l'UNESCO situé en République Démocratique du Congo.  C'est le plus ancien parc national d'Afrique. Il est connu pour abriter les derniers gorilles de montagne. Depuis plusieurs années, le parc est menacé par des activités illégales telles que le braconnage et l'exploration pétrolière. Emmanuel de Merode, le directeur du parc, a joué un rôle clé dans le développement d’un certain nombre de projets liés aux énergies renouvelables dans la région, tels que des centrales hydroélectriques, afin de réduire la dépendance aux combustibles fossiles, et d'améliorer l'accès à l'électricité pour les communautés locales. Le Parc national des Virunga est un site classé au patrimoine mondial de l'UNESCO situé en République Démocratique du Congo.  C'est le plus ancien parc national d'Afrique. Il est connu pour abriter les derniers gorilles de montagne. Depuis plusieurs années, le parc est menacé par des activités illégales telles que le braconnage et l'exploration pétrolière. Emmanuel de Merode, le directeur du parc, a joué un rôle clé dans le développement d’un certain nombre de projets liés aux énergies renouvelables dans la région, tels que des centrales hydroélectriques, afin de réduire la dépendance aux combustibles fossiles, et d'améliorer l'accès à l'électricité pour les communautés locales. Le Parc national des Virunga est un site classé au patrimoine mondial de l'UNESCO situé en République Démocratique du Congo.  C'est le plus ancien parc national d'Afrique. Il est connu pour abriter les derniers gorilles de montagne. Depuis plusieurs années, le parc est menacé par des activités illégales telles que le braconnage et l'exploration pétrolière. Emmanuel de Merode, le directeur du parc, a joué un rôle clé dans le développement d’un certain nombre de projets liés aux énergies renouvelables dans la région, tels que des centrales hydroélectriques, afin de réduire la dépendance aux combustibles fossiles, et d'améliorer l'accès à l'électricité pour les communautés locales.Le Parc national des Virunga est un site classé au patrimoine mondial de l'UNESCO situé en République Démocratique du Congo.  C'est le plus ancien parc national d'Afrique. Il est connu pour abriter les derniers gorilles de montagne. Depuis plusieurs années, le parc est menacé par des activités illégales telles que le braconnage et l'exploration pétrolière. Emmanuel de Merode, le directeur du parc, a joué un rôle clé dans le développement d’un certain nombre de projets liés aux énergies renouvelables dans la région, tels que des centrales hydroélectriques, afin de réduire la dépendance aux combustibles fossiles, et d'améliorer l'accès à l'électricité pour les communautés locales.Le Parc national des Virunga est un site classé au patrimoine mondial de l'UNESCO situé en République Démocratique du Congo.  C'est le plus ancien parc national d'Afrique. Il est connu pour abriter les derniers gorilles de montagne. Depuis plusieurs années, le parc est menacé par des activités illégales telles que le braconnage et l'exploration pétrolière. Emmanuel de Merode, le directeur du parc, a joué un rôle clé dans le développement d’un certain nombre de projets liés aux énergies renouvelables dans la région, tels que des centrales hydroélectriques, afin de réduire la dépendance aux combustibles fossiles, et d'améliorer l'accès à l'électricité pour les communautés locales.`,
    tokenName: 'CleanSat Mining Alpha',
    tokenSymbolName: 'CSM-ALPHA',
    tokenSymbolUrl:
      'https://gnosisscan.io/token/0xf8419b6527A24007c2BD81bD1aA3b5a735C1F4c9',
    smartContractAddress: '0xf8419b6527A24007c2BD81bD1aA3b5a735C1F4c9',
    smartContractAddressUrl:
      'https://gnosisscan.io/token/0xf8419b6527A24007c2BD81bD1aA3b5a735C1F4c9',
    blokchainNetwork: 'Gnosis chain',
    tokenQuantity: 100000,
    shareOfTokenizedCompany: 100,
    ipfsDocumentUrl: '',
    minedBtc: 800000,
    otherIncome: 0,
    electricityCost: 300000,
    operatingCost: 75000,
    csmFees: 25000,
    otherCost: 0,
    equipmentDepreciationCost: 160000,
    is: 32528,
    asics: 800000,
    vat: 200000,
    miscEquipment: 100000,
    transportation: 100000,
    electricityDeposit: 45000,
    otherInvestment: 45000,
    estimatedNetAPY: 0.1608,
    estimatedGrossAPY: 0.1447,
    financeHelpPageUrl: 'https://cleansatmining.com/comprendre',
  },
  featuredAsset: {
    id: '62',
    type: AssetType.IMAGE,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    mimeType: 'test',
    tags: [],
    fileSize: 1024,
    width: 1159,
    height: 773,
    name: 'activity-721-1.jpg',
    preview:
      'http://localhost:3001/assets/preview/22/activity-721-1__preview.jpg',
    source:
      'http://localhost:3001/assets/preview/22/activity-721-1__preview.jpg',
  },
  optionGroups: [],
  slug: 'sample-product',
  translations: [],
  updatedAt: new Date().toISOString(),
  variantList: {
    __typename: 'ProductVariantList',
    items: [],
    totalItems: 10,
  },
  variants: [],
}

export default incomingMockedProduct
