import Footer from '@/app/[locale]/layout/Footer'
import Header from '@/app/[locale]/layout/Header'
import { ApolloWrapper } from '@/lib/ApolloProvider'
import ToastProvider from '@/lib/ToastProvider'
import type { Metadata } from 'next'
import { NextIntlClientProvider, useLocale } from 'next-intl'
import { Cairo, Poppins } from 'next/font/google'
import { notFound } from 'next/navigation'
import { AuthProvider } from '../../lib/AuthProvider'
import '../globals.css'
import Main from './layout/Main'

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['300', '400', '600', '700'],
})

const cairo = Cairo({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-cairo',
  weight: ['400', '600', '700', '800'],
})

export const metadata: Metadata = {
  title: 'Realt CSM',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  const locale = useLocale()
  let messages
  try {
    messages = (await import(`../../../messages/${locale}.json`)).default
  } catch (error) {
    notFound()
  }

  if (params.locale !== locale) {
    notFound()
  }

  return (
    <html
      lang={locale}
      className={`h-full dark ${poppins.variable} ${cairo.variable}`}
    >
      <body className="flex min-h-screen flex-col dark:bg-grey-600 dark:text-white">
        <ApolloWrapper>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <AuthProvider>
              <Header />
              <Main>{children}</Main>
              <Footer />
            </AuthProvider>
            <ToastProvider />
          </NextIntlClientProvider>
        </ApolloWrapper>
      </body>
    </html>
  )
}
